### ISSUE TITLE
[0.12.0] Processing description.ext issue

### ISSUE THREAD

**Issue by Wyqer** [RZSenfo/vscode-sqflint#1]
**Repository:** https://github.com/KillahPotatoes/KP-Liberation/tree/master
**Branch:** master

In this branch the description.ext processing runs endless and the indexing stays at 0%. The output of SQFLint shows just:

```
Indexing workspace...
Parsing: c:\Users\macio\Documents\KP-Liberation\Missionframework\description.ext
Parsed: c:\Users\macio\Documents\KP-Liberation\Missionframework\description.ext
Proccessing: c:\Users\macio\Documents\KP-Liberation\Missionframework\description.ext
```

**Repository:** https://github.com/KillahPotatoes/KP-Liberation/tree/v.0.96.7
**Branch:** v.0.96.7

In our current working branch for the version which will be released in a few days it actually shows an error and crashes.

```
Indexing workspace...
Parsing: c:\Users\macio\Documents\KP-Liberation\Missionframework\description.ext
Parsed: c:\Users\macio\Documents\KP-Liberation\Missionframework\description.ext
Proccessing: c:\Users\macio\Documents\KP-Liberation\Missionframework\description.ext
Error while parsing c:\Users\macio\Documents\KP-Liberation\Missionframework\description.ext SyntaxError: Expected "/*", "//", ";", comment, end of line, or whitespace but ")" found.
    at peg$buildStructuredError (c:\Users\macio\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\grammars\pegjs-hpp.js:403:16)
    at Object.peg$parse [as parse] (c:\Users\macio\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\grammars\pegjs-hpp.js:3238:15)
    at Object.parse (c:\Users\macio\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\hpp.js:17:43)
    at c:\Users\macio\.vscode\extensions\senfo.sqflint-0.12.0\server\modules\ext.js:256:44
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
  message: 'Expected "/*", "//", ";", comment, end of line, or whitespace but ")" found.',
  expected: [
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: ';', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '//', ignoreCase: false },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'whitespace' },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' }
  ],
  found: ')',
  location: {
    start: { offset: 186240, line: 6563, column: 45 },
    end: { offset: 186241, line: 6563, column: 46 }
  },
  name: 'SyntaxError'
} [
  '        class KP_GroupList: KPGUI_PRE_ListBox {',
  '            idc = 758038;',
  '            x = KP_GETCX(KP_X_VAL_C,KP_WIDTH_VAL_C,0,1);',
  '            y = KP_GETCY(KP_Y_VAL_C,KP_HEIGHT_VAL_C,4,16);',
  '            w = KP_GETW(KP_WIDTH_VAL_C,(4/3)); <--- ERROR LINE',
  '            h = KP_GETH(KP_HEIGHT_VAL_C,(24/5));',
  '            onLBSelChanged = "ctrlSetText [758039, groupId (KPPLM_groups select (lbCurSel 758038))]";',
  '        };',
  '',
  '        class KP_ButtonJoin: KPGUI_PRE_InlineButton {',
  '            text = "$STR_KPPLM_JOIN";',
  '            x = KP_GETCX(KP_X_VAL_C,KP_WIDTH_VAL_C,3,4);',
  '            y = KP_GETCY(KP_Y_VAL_C,KP_HEIGHT_VAL_C,4,16);',
  '            w = KP_GETW(KP_WIDTH_VAL_C,4);',
  '            h = KP_GETH(KP_HEIGHT_VAL_C,(48/5));'
]
Starting SQFLint Background-Server
SQFLint: Process crashed Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-jar',
    'c:\\Users\\macio\\.vscode\\extensions\\senfo.sqflint-0.12.0\\bin\\SQFLint.jar',
    '-j',
    '-v',
    '-s'
  ]
}
(node:22648) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at c:\Users\macio\.vscode\extensions\senfo.sqflint-0.12.0\server\sqflint.js:190:37
    at new Promise (<anonymous>)
    at SQFLint.parse (c:\Users\macio\.vscode\extensions\senfo.sqflint-0.12.0\server\sqflint.js:180:16)
(node:22648) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at c:\Users\macio\.vscode\extensions\senfo.sqflint-0.12.0\server\sqflint.js:190:37
    at new Promise (<anonymous>)
    at SQFLint.parse (c:\Users\macio\.vscode\extensions\senfo.sqflint-0.12.0\server\sqflint.js:180:16)
(node:22648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
SQFLint: Process crashed with code -4058
```

The mentioned syntax error in the output is at least a hint. But personally I can't see what SQFLint sees exactly as issue there:
https://github.com/KillahPotatoes/KP-Liberation/blob/v.0.96.7/Missionframework/KP/KPPLM/ui/KPPLM_dialog.hpp#L156

Many thanks for your time and willingness to keep this extension running. 👍

**Comment by mr-guard** [comment]
The issue the parser has is "(4/3)", the ")" to be percise.
Gonna need to alter the regex to fetch that, nothing too bad.

Thanks for the report
