### ISSUE TITLE
[0.12.0] CfgFunctions isn't parsed correctly

### ISSUE THREAD

**Issue by Wyqer** [RZSenfo/vscode-sqflint#2]
**Repository:** https://github.com/KillahPotatoes/KP-Liberation/tree/v.0.96.7
**Branch:** v.0.96.7

SQFLint currently marks all functions as not defined, which leads to showing >1,000 errors.
Format of the functions due to CfgFunction Classes: `KPLIB_fnc_functionName`

Description.ext file:
https://github.com/KillahPotatoes/KP-Liberation/blob/v.0.96.7/Missionframework/description.ext#L38-L41

CfgFunctions file:
https://github.com/KillahPotatoes/KP-Liberation/blob/v.0.96.7/Missionframework/CfgFunctions.hpp

SQFLint Output:
```
Indexing workspace...
Parsing: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
Parsed: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
Proccessing: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
Error while parsing c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext SyntaxError: Expected "/*", "//", ";", comment, end of line, or whitespace but ")" found.
    at peg$buildStructuredError (c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\grammars\pegjs-hpp.js:403:16)
    at Object.peg$parse [as parse] (c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\grammars\pegjs-hpp.js:3238:15)
    at Object.parse (c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\hpp.js:17:43)
    at c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\modules\ext.js:256:44
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
  message: 'Expected "/*", "//", ";", comment, end of line, or whitespace but ")" found.',
  expected: [
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: ';', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '//', ignoreCase: false },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'whitespace' },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' }
  ],
  found: ')',
  location: {
    start: { offset: 186422, line: 6569, column: 45 },
    end: { offset: 186423, line: 6569, column: 46 }
  },
  name: 'SyntaxError'
} [
  '        class KP_GroupList: KPGUI_PRE_ListBox {',
  '            idc = 758038;',
  '            x = KP_GETCX(KP_X_VAL_C,KP_WIDTH_VAL_C,0,1);',
  '            y = KP_GETCY(KP_Y_VAL_C,KP_HEIGHT_VAL_C,4,16);',
  '            w = KP_GETW(KP_WIDTH_VAL_C,(4/3)); <--- ERROR LINE',
  '            h = KP_GETH(KP_HEIGHT_VAL_C,(24/5));',
  '            onLBSelChanged = "ctrlSetText [758039, groupId (KPPLM_groups select (lbCurSel 758038))]";',
  '        };',
  '',
  '        class KP_ButtonJoin: KPGUI_PRE_InlineButton {',
  '            text = "$STR_KPPLM_JOIN";',
  '            x = KP_GETCX(KP_X_VAL_C,KP_WIDTH_VAL_C,3,4);',
  '            y = KP_GETCY(KP_Y_VAL_C,KP_HEIGHT_VAL_C,4,16);',
  '            w = KP_GETW(KP_WIDTH_VAL_C,4);',
  '            h = KP_GETH(KP_HEIGHT_VAL_C,(48/5));'
]
Starting SQFLint Background-Server
Done module index... Now indexing sqf
SQF Parse took long for: file:///c%3A/Users/Agando/Documents/GitHub/KP-Liberation/Missionframework/scripts/server/init_server.sqf (3842 ms)
Parsing a total of sqf 380 files
Starting SQFLint Background-Server
Proccessing: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
Error while parsing c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext SyntaxError: Expected "/*", "//", ";", comment, end of line, or whitespace but ")" found.
    at peg$buildStructuredError (c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\grammars\pegjs-hpp.js:403:16)
    at Object.peg$parse [as parse] (c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\grammars\pegjs-hpp.js:3238:15)
    at Object.parse (c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\hpp.js:17:43)
    at c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\modules\ext.js:256:44
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
  message: 'Expected "/*", "//", ";", comment, end of line, or whitespace but ")" found.',
  expected: [
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: ';', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '//', ignoreCase: false },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'whitespace' },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' }
  ],
  found: ')',
  location: {
    start: { offset: 186422, line: 6569, column: 45 },
    end: { offset: 186423, line: 6569, column: 46 }
  },
  name: 'SyntaxError'
} [
  '        class KP_GroupList: KPGUI_PRE_ListBox {',
  '            idc = 758038;',
  '            x = KP_GETCX(KP_X_VAL_C,KP_WIDTH_VAL_C,0,1);',
  '            y = KP_GETCY(KP_Y_VAL_C,KP_HEIGHT_VAL_C,4,16);',
  '            w = KP_GETW(KP_WIDTH_VAL_C,(4/3)); <--- ERROR LINE',
  '            h = KP_GETH(KP_HEIGHT_VAL_C,(24/5));',
  '            onLBSelChanged = "ctrlSetText [758039, groupId (KPPLM_groups select (lbCurSel 758038))]";',
  '        };',
  '',
  '        class KP_ButtonJoin: KPGUI_PRE_InlineButton {',
  '            text = "$STR_KPPLM_JOIN";',
  '            x = KP_GETCX(KP_X_VAL_C,KP_WIDTH_VAL_C,3,4);',
  '            y = KP_GETCY(KP_Y_VAL_C,KP_HEIGHT_VAL_C,4,16);',
  '            w = KP_GETW(KP_WIDTH_VAL_C,4);',
  '            h = KP_GETH(KP_HEIGHT_VAL_C,(48/5));'
]
Done indexing workspace.
Indexing workspace again, to resolve global variables.
Parsing: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
Parsed: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
Proccessing: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
Error while parsing c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext SyntaxError: Expected "/*", "//", ";", comment, end of line, or whitespace but ")" found.
    at peg$buildStructuredError (c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\grammars\pegjs-hpp.js:403:16)
    at Object.peg$parse [as parse] (c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\grammars\pegjs-hpp.js:3238:15)
    at Object.parse (c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\parsers\hpp.js:17:43)
    at c:\Users\Agando\.vscode\extensions\senfo.sqflint-0.12.0\server\modules\ext.js:256:44
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
  message: 'Expected "/*", "//", ";", comment, end of line, or whitespace but ")" found.',
  expected: [
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: ';', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'literal', text: '//', ignoreCase: false },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'whitespace' },
    { type: 'literal', text: '/*', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' }
  ],
  found: ')',
  location: {
    start: { offset: 186422, line: 6569, column: 45 },
    end: { offset: 186423, line: 6569, column: 46 }
  },
  name: 'SyntaxError'
} [
  '        class KP_GroupList: KPGUI_PRE_ListBox {',
  '            idc = 758038;',
  '            x = KP_GETCX(KP_X_VAL_C,KP_WIDTH_VAL_C,0,1);',
  '            y = KP_GETCY(KP_Y_VAL_C,KP_HEIGHT_VAL_C,4,16);',
  '            w = KP_GETW(KP_WIDTH_VAL_C,(4/3)); <--- ERROR LINE',
  '            h = KP_GETH(KP_HEIGHT_VAL_C,(24/5));',
  '            onLBSelChanged = "ctrlSetText [758039, groupId (KPPLM_groups select (lbCurSel 758038))]";',
  '        };',
  '',
  '        class KP_ButtonJoin: KPGUI_PRE_InlineButton {',
  '            text = "$STR_KPPLM_JOIN";',
  '            x = KP_GETCX(KP_X_VAL_C,KP_WIDTH_VAL_C,3,4);',
  '            y = KP_GETCY(KP_Y_VAL_C,KP_HEIGHT_VAL_C,4,16);',
  '            w = KP_GETW(KP_WIDTH_VAL_C,4);',
  '            h = KP_GETH(KP_HEIGHT_VAL_C,(48/5));'
]
Done module index... Now indexing sqf
Parsing a total of sqf 380 files
Starting SQFLint Background-Server
Done reindexing workspace.
```
Error messages are connected to #1

**Comment by mr-guard** [comment]
should be fixed in 0.13.7

**Comment by Wyqer** [comment]
Doesn't seem so on my end.
Indexing in the bar stays at 0%.
Log doesn't say anything strange:
```
Indexing workspace...
Starting SQFLint Background-Server
Started SQFLint Background-Server
Parsing: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
Parsed: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
Proccessing: c:\Users\Agando\Documents\GitHub\KP-Liberation\Missionframework\description.ext
```

**Comment by Wyqer** [comment]
Works fine on other repositories, so it seems to be something "special" in that framework. Would be fine to leave it as "not a plugin issue in general", beside of the fact that I would be curious what really blocks the indexing. We're currently refactoring many things, so it might also be gone after that ~5 years old code leftovers are gone. Who knows?

**Comment by mr-guard** [comment]
could be
If the indexing gets stuck, most likely a loop doesnt exit. However I cannot tell you why without looking at some more verbose logs
